// Builds data/territories.json and data/setup.json from the TripleA
// "World War II Classic" map XML (data/source/triplea-classic.xml,
// https://github.com/triplea-maps/world_war_ii_classic — 2nd-edition rules).
//
// Provenance: map graph, IPC production values, initial owners, initial unit
// placement and starting IPCs all come from the XML. ENGINE RULES do NOT come
// from here (TripleA deviates from Classic in places, e.g. it destroys
// captured factories/AA guns; Classic captures them) — rules live in the
// engine, cited to the 2nd-edition rulebook PDF.
//
// Run: node scripts/build-data.mjs   (re-runnable; never hand-edit outputs)
import { readFileSync, writeFileSync } from 'node:fs';

const xml = readFileSync(new URL('../data/source/triplea-classic.xml', import.meta.url), 'utf8');

const POWER = { Russians: 'russia', Germans: 'germany', British: 'uk', Japanese: 'japan', Americans: 'usa' };
const id = (name) =>
  name.toLowerCase().replace(/['.]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

// --- territories ---
const territories = new Map();
for (const m of xml.matchAll(/<territory name="([^"]+)"( water="true")?\s*\/>/g)) {
  territories.set(m[1], { id: id(m[1]), name: m[1], water: !!m[2], ipc: 0, originalOwner: null, connections: [] });
}

// --- production values ---
for (const m of xml.matchAll(/<attachment name="territoryAttachment" attachTo="([^"]+)"[^>]*>\s*<option name="production" value="(\d+)"\/>/g)) {
  const t = territories.get(m[1]);
  if (!t) throw new Error(`production for unknown territory ${m[1]}`);
  t.ipc = Number(m[2]);
}

// --- connections (undirected) ---
for (const m of xml.matchAll(/<connection t1="([^"]+)" t2="([^"]+)"\/>/g)) {
  const a = territories.get(m[1]), b = territories.get(m[2]);
  if (!a || !b) throw new Error(`connection with unknown territory: ${m[1]} / ${m[2]}`);
  a.connections.push(b.id);
  b.connections.push(a.id);
}

// --- initial owners ---
for (const m of xml.matchAll(/<territoryOwner territory="([^"]+)" owner="([^"]+)"\/>/g)) {
  const t = territories.get(m[1]);
  if (!t) throw new Error(`owner for unknown territory ${m[1]}`);
  t.originalOwner = POWER[m[2]] ?? (() => { throw new Error(`unknown power ${m[2]}`); })();
}

// --- initial units ---
const UNIT = {
  infantry: 'infantry', armour: 'armor', fighter: 'fighter', bomber: 'bomber',
  transport: 'transport', battleship: 'battleship', carrier: 'carrier',
  submarine: 'submarine', factory: 'factory', aaGun: 'aaGun',
};
const placements = [];
for (const m of xml.matchAll(/<unitPlacement unitType="([^"]+)" territory="([^"]+)" quantity="(\d+)" owner="([^"]+)"\/>/g)) {
  const t = territories.get(m[2]);
  if (!t) throw new Error(`placement in unknown territory ${m[2]}`);
  const unit = UNIT[m[1]] ?? (() => { throw new Error(`unknown unit ${m[1]}`); })();
  placements.push({ territory: t.id, unit, count: Number(m[3]), owner: POWER[m[4]] });
}

// --- starting IPCs ---
const ipcs = {};
for (const m of xml.matchAll(/<resourceGiven player="([^"]+)" resource="PUs" quantity="(\d+)"\/>/g)) {
  ipcs[POWER[m[1]]] = Number(m[2]);
}

// sanity checks
const list = [...territories.values()].sort((a, b) => a.id.localeCompare(b.id));
for (const t of list) {
  t.connections = [...new Set(t.connections)].sort();
  if (t.connections.length === 0) throw new Error(`isolated territory: ${t.name}`);
  if (t.water && t.originalOwner) throw new Error(`owned sea zone: ${t.name}`);
}
const ids = new Set(list.map((t) => t.id));
if (ids.size !== list.length) throw new Error('duplicate territory ids');

writeFileSync(new URL('../data/territories.json', import.meta.url),
  JSON.stringify({ _provenance: 'generated by scripts/build-data.mjs from triplea-classic.xml — do not hand-edit', territories: list }, null, 2));
writeFileSync(new URL('../data/setup.json', import.meta.url),
  JSON.stringify({ _provenance: 'generated by scripts/build-data.mjs from triplea-classic.xml — do not hand-edit', startingIpcs: ipcs, placements }, null, 2));

console.log(`territories: ${list.length} (${list.filter(t => t.water).length} sea), placements: ${placements.length}, total income check:`,
  Object.fromEntries(Object.entries(POWER).map(([, p]) => [p, list.filter(t => t.originalOwner === p).reduce((s, t) => s + t.ipc, 0)])));
